<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PessoaResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'tipo_registro' => $this->tipo_registro,
            'codigo_escola_inep' => $this->codigo_escola_inep,
            'codigo_pessoa_fisica_sistema_proprio' => $this->codigo_pessoa_fisica_sistema_proprio,
            'identificacao_unica_inep' => $this->identificacao_unica_inep,
            'numero_cpf' => $this->numero_cpf,
            'nome_completo' => $this->nome_completo,
            'data_nascimento' => $this->data_nascimento,
            'filiacao' => $this->filiacao,
            'filiacao_1' => $this->filiacao_1,
            'filiacao_2' => $this->filiacao_2,
            'sexo' => $this->sexo,
            'cor_raca' => $this->cor_raca,
            'nacionalidade' => $this->nacionalidade,
            'pais_nacionalidade' => $this->pais_nacionalidade,
            'municipio_nascimento' => $this->municipio_nascimento,
            'pessoa_fisica_com_deficiencia_ou_transtorno' => $this->pessoa_fisica_com_deficiencia_ou_transtorno,
            'pessoa_fisica_com_deficiencia_ou_transtorno_autismo' => $this->pessoa_fisica_com_deficiencia_ou_transtorno_autismo,
            'cegueira' => $this->cegueira,
            'baixa_visao' => $this->baixa_visao,
            'visao_monocular' => $this->visao_monocular,
            'surdez' => $this->surdez,
            'deficiencia_auditiva' => $this->deficiencia_auditiva,
            'surdocegueira' => $this->surdocegueira,
            'deficiencia_fisica' => $this->deficiencia_fisica,
            'deficiencia_intelectual' => $this->deficiencia_intelectual,
            'deficiencia_multipla' => $this->deficiencia_multipla,
            'transtorno_espectro_autista' => $this->transtorno_espectro_autista,
            'altas_habilidades_superdotacao' => $this->altas_habilidades_superdotacao,
            'auxilio_ledor' => $this->auxilio_ledor,
            'auxilio_transcricao' => $this->auxilio_transcricao,
            'guia_interprete' => $this->guia_interprete,
            'tradutor_interprete_libras' => $this->tradutor_interprete_libras,
            'leitura_labial' => $this->leitura_labial,
            'prova_ampliada' => $this->prova_ampliada,
            'prova_superampliada' => $this->prova_superampliada,
            'cd_audio_deficiente_visual' => $this->cd_audio_deficiente_visual,
            'prova_lingua_portuguesa_segunda_lingua' => $this->prova_lingua_portuguesa_segunda_lingua,
            'prova_video_libras' => $this->prova_video_libras,
            'material_didatico_prova_braille' => $this->material_didatico_prova_braille,
            'nenhum_recurso' => $this->nenhum_recurso,
            'numero_matricula_certidao_nascimento' => $this->numero_matricula_certidao_nascimento,
            'pais_residencia' => $this->pais_residencia,
            'cep' => $this->cep,
            'municipio_residencia' => $this->municipio_residencia,
            'localizacao_zona_residencia' => $this->localizacao_zona_residencia,
            'localizacao_diferenciada_residencia' => $this->localizacao_diferenciada_residencia,
            'maior_nivel_escolaridade_concluido' => $this->maior_nivel_escolaridade_concluido,
            'tipo_ensino_medio_cursado' => $this->tipo_ensino_medio_cursado,
            'codigo_curso_1' => $this->codigo_curso_1,
            'ano_conclusao_1' => $this->ano_conclusao_1,
            'instituicao_educacao_superior_1' => $this->instituicao_educacao_superior_1,
            'codigo_curso_2' => $this->codigo_curso_2,
            'ano_conclusao_2' => $this->ano_conclusao_2,
            'instituicao_educacao_superior_2' => $this->instituicao_educacao_superior_2,
            'codigo_curso_3' => $this->codigo_curso_3,
            'ano_conclusao_3' => $this->ano_conclusao_3,
            'instituicao_educacao_superior_3' => $this->instituicao_educacao_superior_3,
            'area_conhecimento_componentes_curriculares_1' => $this->area_conhecimento_componentes_curriculares_1,
            'area_conhecimento_componentes_curriculares_2' => $this->area_conhecimento_componentes_curriculares_2,
            'area_conhecimento_componentes_curriculares_3' => $this->area_conhecimento_componentes_curriculares_3,
            'tipo_pos_graduacao_1' => $this->tipo_pos_graduacao_1,
            'area_pos_graduacao_1' => $this->area_pos_graduacao_1,
            'ano_conclusao_pos_graduacao_1' => $this->ano_conclusao_pos_graduacao_1,
            'tipo_pos_graduacao_2' => $this->tipo_pos_graduacao_2,
            'area_pos_graduacao_2' => $this->area_pos_graduacao_2,
            'ano_conclusao_pos_graduacao_2' => $this->ano_conclusao_pos_graduacao_2,
            'tipo_pos_graduacao_3' => $this->tipo_pos_graduacao_3,
            'area_pos_graduacao_3' => $this->area_pos_graduacao_3,
            'ano_conclusao_pos_graduacao_3' => $this->ano_conclusao_pos_graduacao_3,
            'tipo_pos_graduacao_4' => $this->tipo_pos_graduacao_4,
            'area_pos_graduacao_4' => $this->area_pos_graduacao_4,
            'ano_conclusao_pos_graduacao_4' => $this->ano_conclusao_pos_graduacao_4,
            'tipo_pos_graduacao_5' => $this->tipo_pos_graduacao_5,
            'area_pos_graduacao_5' => $this->area_pos_graduacao_5,
            'ano_conclusao_pos_graduacao_5' => $this->ano_conclusao_pos_graduacao_5,
            'tipo_pos_graduacao_6' => $this->tipo_pos_graduacao_6,
            'area_pos_graduacao_6' => $this->area_pos_graduacao_6,
            'ano_conclusao_pos_graduacao_6' => $this->ano_conclusao_pos_graduacao_6,
            'nao_tem_pos_graduacao_concluida' => $this->nao_tem_pos_graduacao_concluida,
            'creche' => $this->creche,
            'pre_escola' => $this->pre_escola,
            'anos_iniciais_ensino_fundamental' => $this->anos_iniciais_ensino_fundamental,
            'anos_finais_ensino_fundamental' => $this->anos_finais_ensino_fundamental,
            'ensino_medio' => $this->ensino_medio,
            'educacao_jovens_adultos' => $this->educacao_jovens_adultos,
            'educacao_especial' => $this->educacao_especial,
            'educacao_indigena' => $this->educacao_indigena,
            'educacao_campo' => $this->educacao_campo,
            'educacao_ambiental' => $this->educacao_ambiental,
            'educacao_direitos_humanos' => $this->educacao_direitos_humanos,
            'educacao_bilingue_surdos' => $this->educacao_bilingue_surdos,
            'educacao_tecnologia_informacao_comunicacao' => $this->educacao_tecnologia_informacao_comunicacao,
            'genero_diversidade_sexual' => $this->genero_diversidade_sexual,
            'direitos_crianca_adolescente' => $this->direitos_crianca_adolescente,
            'educacao_relacoes_etnico_raciais_historia_afro' => $this->educacao_relacoes_etnico_raciais_historia_afro,
            'gestao_escolar' => $this->gestao_escolar,
            'outros' => $this->outros,
            'nenhum' => $this->nenhum,
            'endereco_eletronico_email' => $this->endereco_eletronico_email,
            'role' => $this->role,
            'escola_id' => $this->escola_id,
            'secretaria_id' => $this->secretaria_id,
            'turma_id' => $this->turma_id,
            'responsavel_id' => $this->responsavel_id,
            'created_at' => $this->created_at
                ? $this->created_at->timezone('America/Sao_Paulo')->toDateTimeString()
                : null,
            'updated_at' => $this->updated_at
                ? $this->updated_at->timezone('America/Sao_Paulo')->toDateTimeString()
                : null,
        ];
    }
}
